# fly.toml app configuration file generated for yeehaa-landing on 2023-05-19T18:08:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yeehaa-landing"
primary_region = "ams"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "yeehaa-landing.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
